michael updated assemble

diff --git a/s2i-scripts/.s2i/bin/assemble b/s2i-scripts/.s2i/bin/assemble
--- a/s2i-scripts/.s2i/bin/assemble
+++ b/s2i-scripts/.s2i/bin/assemble
@@ -1,41 +1,15 @@
 #!/bin/bash
 
-set -e
+echo "call builder image assemble"
+/usr/libexec/s2i/assemble
 
-source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh
+rc=$?
 
-echo "---> Enabling s2i support in httpd24 image"
-
-config_s2i
-
-######## CUSTOMIZATION STARTS HERE ############
-
-echo "---> Installing application source"
-cp -Rf /tmp/src/*.html ./
-
-DATE=`date "+%b %d, %Y @ %H:%M %p"`
-
-echo "---> Creating info page"
-echo "Michael Page built on $DATE" >> ./info.html
-echo "Proudly served by Apache HTTP Server version $HTTPD_VERSION" >> ./info.html
-
-######## CUSTOMIZATION ENDS HERE ############
-
-if [ -d ./httpd-cfg ]; then
-  echo "---> Copying httpd configuration files..."
-  if [ "$(ls -A ./httpd-cfg/*.conf)" ]; then
-    cp -v ./httpd-cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-    rm -rf ./httpd-cfg
-  fi
+if [$rc -eq 0]; then
+  echo "call builder image assemble successfully and copy index file"
+  cp /tmp/src/index.html ./index2.html
 else
-  if [ -d ./cfg ]; then
-    echo "---> Copying httpd configuration files from deprecated './cfg' directory, use './httpd-cfg' instead..."
-    if [ "$(ls -A ./cfg/*.conf)" ]; then
-      cp -v ./cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-      rm -rf ./cfg
-    fi
-  fi
+  echo "call builder image assemble failed"
 fi
 
-# Fix source directory permissions
-fix-permissions ./
+exit $rc
